event/urls.py
from django.urls import path
from . import views
from django.conf.urls import url
from event import views as core_views


urlpatterns = [
    path('', views.index, name = "index"),
    path('signup/', core_views.signup, name='signup'),
    path('events/', views.EventListView.as_view(), name="events"),
    path('event/create', views.EventCreateView.as_view(), name="event-create"),
    path('event/<int:pk>', views.EventDetailView.as_view(), name="event-detail"),
    path('event/<int:pk>/update', views.EventUpdateView.as_view(), name="event-update"),
    path('event/<int:pk>/delete', views.EventDeleteView.as_view(), name="event-delete"),
    path('event/<int:pk>/eventattendence_create', views.EventAttendenceCreate.as_view(), name='add-attendence'),
    path('event/<int:pk>/event_attendence_list', views.EventAttendenceListView.as_view(), name='attendence-list'),
    path('event/event_attendence_detail/<int:pk>', views.EventAttendenceDetailView.as_view(), name='attendence-detail')
]

# from django.conf.urls import url
# from event import views as core_views

# urlpatterns = [
#     url(r'^signup/$', core_views.signup, name='signup'),
# ]

eventproject/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('event/', include('event.urls')),
    path('', RedirectView.as_view(url='event/', permanent=True)),
] + static(settings.IMAGE_URL, document_root=settings.IMAGE_ROOT)

urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

event/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

# Create your models here.
class EventCreator(models.Model):
    user = models.OneToOneField(User, on_delete=models.SET_NULL, null=True)
    date_of_birth = models.DateField(null=True, blank=True)

    class Meta:
        ordering = ["user", "date_of_birth"]
    
    def __str__(self):
        return self.user.username
    
    def get_absolute_url(self):
        return reverse("eventcreator-detail", args=[str(self.id)])

class Event(models.Model):
    name = models.CharField(max_length=200)
    teacher = models.ForeignKey(EventCreator, on_delete=models.CASCADE, blank=True)
    about = models.TextField(help_text="Enter about of event")
    date_of_start = models.DateField(null=True, blank=True)
    date_of_end = models.DateField('ended', null=True, blank=True)

    def __str__(self):
        return self.name
    
    class Meta:
        ordering = ['id', 'name', 'date_of_start']
    
    def get_absolute_url(self):
        return reverse("event-detail", args=[str(self.id)])

class EventAttendence(models.Model):
    profile = models.ImageField(upload_to='images/', default='defo')
    name = models.CharField(max_length=1000, help_text="Enter your Name")
    email = models.EmailField(max_length=70,blank=True,unique=True)
    date_of_birth = models.DateField(null=True, blank=True)
    phone_no = models.CharField(max_length=12)
    event = models.ForeignKey(Event, on_delete=models.CASCADE, blank=True)

    class Meta:
        ordering = ["name"]

event/views.py
from django.shortcuts import render, get_object_or_404, redirect
from event.models import Event, EventCreator, EventAttendence
from django.contrib.auth.models import User
from django.views import generic
from django.urls import reverse, reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import UserCreationForm

# Create your views here.
def index(request):
    return render(request, 'index.html')

class EventListView(LoginRequiredMixin, generic.ListView):
    model = Event
    paginate_by = 5

class EventDetailView(LoginRequiredMixin, generic.DetailView):
    model = Event

class EventCreateView(LoginRequiredMixin, generic.CreateView):
    model = Event
    fields = ['name','teacher', 'about', 'date_of_start', 'date_of_end']

    def get_initial(self):
        initial = super().get_initial()
        print(self.request.user)
        initial['teacher'] = EventCreator.objects.get(user = self.request.user)
        return initial

class EventUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Event
    fields = '__all__'

class EventDeleteView(generic.DeleteView):
    model = Event
    success_url = reverse_lazy('events')

class EventAttendenceCreate(LoginRequiredMixin, generic.CreateView):
    model = EventAttendence
    attendence = EventAttendence.objects.all()
    fields = ['profile', 'name', 'email', 'date_of_birth', 'phone_no', 'event']
    
    def get_initial(self, **kwargs):
        initial = super().get_initial()
        initial['event'] = Event.objects.get(pk=self.kwargs["pk"])
        initial['name'] = self.request.user
        return initial
    
    def get_context_data(self, **kwargs):
        context = super(EventAttendenceCreate, self).get_context_data(**kwargs)
        context["event"] = get_object_or_404(Event, pk=self.kwargs['pk'])
        return context

    def get_success_url(self):
        return reverse('attendence-list', kwargs={'pk': self.kwargs['pk'],})

class EventAttendenceListView(generic.ListView):
    model = EventAttendence

class EventAttendenceDetailView(generic.DetailView):
    model = EventAttendence

def signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('events')
    else:
        form = UserCreationForm()
    return render(request, 'signup.html', {'form': form})

event/templates/base_generic.html
<!DOCTYPE html>
<html lang="en">
<head>
    
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    
    {% block title %}<title>Welcome Event</title>{% endblock %}
</head>
<body>
    {% block navbar %}
        <nav class="navbar navbar-expand-lg navbar-light bg-primary">
            <a class="navbar-brand" href="#">Event</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item active">
                            <a class="nav-link" href="{% url 'index' %}">Home<span class="sr-only">(current)</span></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'events' %}">All Events</a>
                        </li>
                    </ul>
                    <ul class="navbar-nav">
                        {% if user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link">Hello:{{ user.get_username }}</a>
                        </li>
                        <li class="nav-item">
                            <a class="btn btn-primary" href="{% url 'event-create' %}">Event Create</a>
                        </li>
                        <li class="nav-item"></li>
                            <a class="btn btn-primary" href="{% url 'password_reset' %}">Password Reset</a>
                        </li>
                        <li class="nav-item">
                            <a class="btn btn-primary" href="{% url 'logout'%}?next={{request.path}}">Logout</a>
                        </li>
                        {% else %}
                        <li class="nav-item">
                            <a class="btn btn-primary" href="{% url 'login'%}?next={{request.path}}">Login</a>
                        </li>
                        <li class="nav-item">
                            <a class="btn btn-primary" href="{% url 'signup'%}">SignUp</a>
                        </li>
                        {% endif %}
                    </ul>
                </div>
        </nav>
        {% endblock %}
            <div class="col-sm-10 ">{% block content %}{% endblock %}
                {% block pagination %}
                    {% if is_paginated %}
                        <div class="pagination">
                            <span class="page-links">
                                {% if page_obj.has_previous %}
                                    <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">previous</a>
                                {% endif %}
                                <span class="page-current">
                                    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                                </span>
                                {% if page_obj.has_next %}
                                    <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">next</a>
                                {% endif %}
                            </span>
                        </div>
                    {% endif %}
                {% endblock %}
            </div>
</body>
</html>

event/templates/event/event_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Delete Event</h1>

<p>Are you sure you want to delete the event: <strong>{{ event.name }}?</strong></p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete.">
</form>

{% endblock %}

event/templates/event/event_detail.html
{% extends "base_generic.html" %}

{% block content %}
    <table class="table">
        <tr>
            <th>Event Title</th>
            <th>Teacher</th>
            <th>About of Event</th>
            <th>Start Date</th>
            <th>End Date</th>
            <th>Number of Attendence</th>
            <th></th>
            <th></th>
            <th></th>
        </tr>
        <tr>
            <td>{{ event.name }}</td>
            <td>{{ event.teacher }}</td>
            <td>{{ event.about }}</td>
            <td>{{ event.date_of_start }}</td>
            <td>{{ event.date_of_end }}</td>
            {% if user == event.teacher.user %}
                <td><a href="{% url 'attendence-list' event.id %}">{{ event.eventattendence_set.count }}</a></td>
            {% else %}
            <td>{{ event.eventattendence_set.count }}</td>
            {% endif %}
            {% if user == event.teacher.user %}    
                <td><a href="{% url 'event-update' event.id %}">Update</a></td>
                <td><a href="{% url 'event-delete' event.id %}">Delete</a></td>
            {% else %}
                <td><a href="{% url 'add-attendence' event.id %}">Join</a></td>
            {% endif %}
        </tr>
    </table>
{% endblock %}

event/templates/event/event_form.html
{% extends "base_generic.html" %}

{% block content %}
  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input class="btn btn-primary" type="submit" value="Submit">
  </form>
{% endblock %}

event/templates/event/event_list.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>All Events</h1>
    {% if event_list %}
        <table class="table">
            <tr>
                <th>#</th>
                <th>Event Name</th>
            </tr>
            {% for event in event_list %}
            <tr>
                <td>{{ event.id }}</td>
                <td><a href="{{ event.get_absolute_url }}">{{ event.name }}</a></td>
            </tr>
            {% endfor %}
        </table>
    {% endif %}
{% endblock %}

event/templates/event/eventattendence_detail.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>EventAttendence Detail</h1>
    <table class="table table-striped">
        <thead>
            <tr>
                <th>Name</th>
                <th>Profile</th>
                <th>Email</th>
                <th>Birthday</th>
                <th>Phone No</th>
                <th>Event</th>
            </tr>
        </thead>
        <tr>
            <td>{{ eventattendence.name }}</a></td>
            <td><img src="{{ eventattendence.profile.url }}" width="100" height="100"/></td>
            <td>{{ eventattendence.email }}</td>
            <td>{{ eventattendence.date_of_birth }}</td>
            <td>{{ eventattendence.phone_no}}</td>
            <td>{{ eventattendence.event }}</td>
        </tr>
    </table>
{% endblock %}

event/templates/event/eventattendence_form.html
{% extends "base_generic.html" %}

{% block content %}
    <p>Fill your profile for:{{ event.name }}</p>
    <form action="" method="post" enctype="multipart/form-data">
        <div class="form-group">
        {% csrf_token %}
        <table>
        {{ form.as_table }}
        </table>
        </div>
        <input class="btn btn-primary" type="submit" value="Submit">
    </form>
{% endblock %}

event/templates/event/eventattendence_list.html
{% extends "base_generic.html" %}

{% block content %}
    {% if eventattendence_list %}
    <h1>Attendence List</h1>
    <table class="table table-striped">
        <thead>
            <tr>
                <th>Name</th>
                <th>Profile</th>
                <th>Attendence Detail</th>
            </tr>
        </thead>
        {% for eventattendence in eventattendence_list %}
        <tr>
            {% if user == eventattendence.event.teacher.user %}
            <td>{{ eventattendence.name }}</a></td>
            <td><img src="{{ eventattendence.profile.url }}" width="100" height="100"/></td>
                <td><a href="{% url 'attendence-detail' eventattendence.id %}">Details</a></td>
            {% endif %}
        </tr>
        {% endfor %}
    </table>
    {% endif %}
{% endblock %}

event/templates/index.html
{% extends "base_generic.html" %}

{% block title %} <title>Event Index</title>{% endblock %}

{% block content %}
    <h1>Event Home</h1>
    <p>Welcome to my Events</p>
{% endblock %}

event/templates/signup.html
{% extends "base_generic.html" %}

{% block content %}
  <h2>Sign up</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Sign up</button>
  </form>
{% endblock %}